name: Cypress Tests using Cypress Docker Image with allure-report

on:
    push:
        branches: [main]

jobs:
    Run_test:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [16.x]

        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "npm"
            - run: npm i npm@latest
            - run: npm i
            - name: run test
              run: npx cypress run
            - name: Create Report
              if: always()
              run: npm run allure:generate
            - name: Upload artifact allure-report
              uses: actions/upload-artifact@v1
              if: always()
              with:
                  name: allure-report
                  path: ./allure-report
            - name: Deploy report
              uses: JamesIves/github-pages-deploy-action@3.1.0
              if: always()
              with:
                  ACCESS_TOKEN: ${{'secrets.ACCESS_TOKEN'}}
                  BRANCH: main # The branch the action should deploy to.
                  FOLDER: allure-report # The folder the action should deploy.
                  TARGET_FOLDER: docs
